### ISSUE TITLE
MoJS curve editor fails on getEasing

### ISSUE THREAD

**Issue by jlamber4** [legomushroom/mojs-curve-editor#3]
I've bene trying to debug this for the last hour, and I can't seem to find out why this parent object is null. My setup is pretty basic, but it is running inside an angular service.

> mojs-curve-editor.js:280 Uncaught TypeError: Cannot read property '_o' of undefined_updateParent @ mojs-curve-editor.js:280_fireOnChange @ mojs-curve-editor.js:270(anonymous function) @ mojs-> curve-editor.js:319
> mojs-curve-editor.js:280 Uncaught TypeError: Cannot read property '_o' of undefined_updateParent @ mojs-curve-editor.js:280_fireOnChange @ mojs-curve-editor.js:270(anonymous function) @ mojs-curve-editor.js:255

Exception location:

```
else if (parent._o.callbacksContext){
```

```
key: '_updateParent',
        value: function _updateParent(easing) {
          var parent = easing._parent;

          if (parent && parent.setProgress) {
            this._triggerParent(parent);
          } else if (parent._o.callbacksContext){
            this._triggerParent(parent._o.callbacksContext.timeline);
          } else if (parent.timeline) {
            this._triggerParent(parent.timeline);
          } else if (parent.tween) {
            this._triggerParent(parent.tween);
          }
        }
```

Offending calling code:

```
const parentElement = document.getElementById("js-el");
  const mojsCurve = new MojsCurveEditor({
    name:         'b curve'
  });

  const rect = new mojs.Shape({
    shape:        'rect',

    left:         {'0%':'100%'},
    top:          0,
    fill:         'none',
    radius:       20,
    stroke:       { 'rgba(0,255,255, 1)' : 'magenta',  easing: mojsCurve.getEasing() },
    strokeWidth:  { 10: 0 },
    strokeDasharray: '100%',
    strokeDashoffset: { '-100%' : '100%' },
    angle:        { 0: 180 },

    duration:     1500,
  });

 $scope.mainTimeline.add( rect );
  const mojsPlayer = new MojsPlayer({ add: $scope.mainTimeline });
```

I only get the exception when mojsCurve.getEasing() is used - otherwise there are no exceptions thrown on initialization.

Using 
mojs - 0.288.1
mojs-curve-editor - 1.4.3
mojs-player - 0.43.15

FWIW
angular 1.4.3

**Comment by legomushroom** [comment]
Hi @jlamber4!

Sorry about that! Indeed this is internal `mojs-curve-editor` issue. I've pushed `1.4.5` version a moment ago that solves it, please grab the `1.4.5` and update the dependency of your project. 

Hope it helps!

**Comment by jlamber4** [comment]
Thanks for the quick update. I have 1.4.5 and the exception is no longer thrown. However the curve editor UI is not showing up on the page - is there a function I need to call to have the ui show? Inspecting page source doesnt show any elements related to a curve editor present.

```
  const mojsCurve = new MojsCurveEditor({name:'logo scale', isSaveState:  true});

  const logo = new mojs.Shape({
    parent: parentElement,
    shape:    'yolobelogo',
    fill:     'none',
    stroke:   'white',
    x:      { 100: 100, curve: mojsCurve.getEasing() },
    scale:    { 1 : 2 },
    strokeWidth: { 1 : 1 },
    strokeDasharray: '100%',
    strokeDashoffset: { '-100%' : '100%' },
    y:         0 ,
    duration:  1000,
  }).then({
    strokeDasharray: {to: '0%', easing: 'bounce.out'},
    strokeDashoffset: {to: '-100%', easing: 'sin.in'},
    duration:  1000,
  });


  $scope.mainTimeline.add( logo );
```

I took the curve: function() call from the readme, and figured that was enough to cause the UI to be bootstrapped?

**Comment by legomushroom** [comment]
You are welcome, @jlamber4 ! 

This line is enough for editor to be shown:

``` javascript
const mojsCurve = new MojsCurveEditor({name:'logo scale', isSaveState:  true});
```

It is very strange it doesn't show up show up for you. Any error in console? Could you set up `isSaveState` to `false` and refresh page couple times, maybe something wrong with `localStorage` record?

Thanks

**Comment by legomushroom** [comment]
update: [codepen example](http://codepen.io/sol0mka/pen/GjxavO?editors=0010)

**Comment by jlamber4** [comment]
Ok yeah, I see on the codepen it shows up on my machine. Still not sure what Im missing when I write it (do I have to use babel?) 
- I shrank it down to the most basic html example and the curve edtior doesnt show up:

```
<!DOCTYPE html>
<html>
<head>
    <title>Anim Test</title>
    <script type="text/javascript" src='https://code.jquery.com/jquery-3.1.1.min.js'></script>
</head>
<body>

<div id='js-welcome-anim-el'></div>
<div id='js-welcome-anim-points'>Curve Editors</div>
<script src="http://cdn.jsdelivr.net/mojs/latest/mo.min.js"></script>
<script src="http://cdn.jsdelivr.net/mojs-player/latest/mojs-player.min.js"></script>
<script src="http://cdn.jsdelivr.net/mojs-curve-editor/latest/mojs-curve-editor.min.js"></script>

<script>
jQuery(function($){

  var mainTimeline = new mojs.Timeline({});
  const parentElement = document.getElementById("js-welcome-anim-el");

  const mojsCurve = new MojsCurveEditor({name:'aSampleEditr', isSaveState:  true});

  const logo = new mojs.Shape({
    parent: parentElement,
    shape:    'circle',
    fill:     'none',
    stroke:   'black',
    scale:    { 1 : 2, easing: mojsCurve.getEasing() },
    strokeWidth: { 1 : 1 },
    strokeDasharray: '100%',
    strokeDashoffset: { '-100%' : '100%' },
    y:         0 ,
    duration:  800,
  }).then({
    strokeDashoffset: {to: '-300%'},
    duration:  800,
    repeat: 999,
  });
  mainTimeline.add( logo );
  const mojsPlayer = new MojsPlayer({ add: mainTimeline });
});
</script>

</body>
</html>
```

**Comment by legomushroom** [comment]
@jlamber4 found out that it works just fine if you construct it outside the `Jquery(function($){})` call. That's an interesting catch, sorry about that. I will fix it shortly, meanwhile, could you use it without the wrapper?

**Comment by legomushroom** [comment]
``` html
<!DOCTYPE html>
<html>
<head>
    <title>Anim Test</title>
</head>
<body>

<div id='js-welcome-anim-el'></div>
<div id='js-welcome-anim-points'>Curve Editors</div>

<script type="text/javascript" src='https://code.jquery.com/jquery-3.1.1.min.js'></script>
<script src="http://cdn.jsdelivr.net/mojs/latest/mo.min.js"></script>
<script src="https://cdn.jsdelivr.net/mojs-curve-editor/1.4.5/mojs-curve-editor.min.js"></script>

<script>
  const mojsCurve = new MojsCurveEditor({ name: 'aSampleEditr' });
  // versus
  // jQuery(function($){ const mojsCurve = new MojsCurveEditor({ name: 'aSampleEditr' }); });
</script>

</body>
</html>
```

**Comment by jlamber4** [comment]
@legomushroom Ah if only I could! In my production app, the curve editor is being created inside an angular controller, which exhibits the same symptoms.

**Comment by legomushroom** [comment]
Ok, Lon do my best to fix it as soon as possible then.

**Comment by jlamber4** [comment]
@legomushroom thank you - your work is very appreciated. I think mojs is a fantastic library and these tools are really well done.

**Comment by legomushroom** [comment]
@jlamber4 thanks! just pushed the `1.4.6` version that solves the issue. Will be available at `jsdelivr` in couple minutes. 

The issue was is that `mojs-curve-editor` is using `DOMContentLoaded` event and renders itself into `DOM` when the event fires. So obviously if you wrap it with another event listener - you will not catch this event twice thus it won't show up. Now works just fine, though.

Sorry about the difficulties and thanks for the alert! 👍

**Comment by jlamber4** [comment]
@legomushroom TYVM works like a charm now.
